import * as path from "path";
import { ITestSuit } from "../index";

const FILES = [
  "./app.wxss",
  "./page/API/animation/animation.wxss",
  "./page/API/background-audio/background-audio.wxss",
  "./page/API/canvas/canvas.wxss",
  "./page/API/download-file/download-file.wxss",
  "./page/API/file/file.wxss",
  "./page/API/get-location/get-location.wxss",
  "./page/API/get-network-type/get-network-type.wxss",
  "./page/API/get-system-info/get-system-info.wxss",
  "./page/API/get-user-info/get-user-info.wxss",
  "./page/API/image/image.wxss",
  "./page/API/index/index.wxss",
  "./page/API/login/login.wxss",
  "./page/API/navigation-bar-loading/navigation-bar-loading.wxss",
  "./page/API/navigator/navigator.wxss",
  "./page/API/on-accelerometer-change/on-accelerometer-change.wxss",
  "./page/API/on-compass-change/on-compass-change.wxss",
  "./page/API/open-location/open-location.wxss",
  "./page/API/pull-down-refresh/pull-down-refresh.wxss",
  "./page/API/request/request.wxss",
  "./page/API/request-payment/request-payment.wxss",
  "./page/API/set-navigation-bar-title/set-navigation-bar-title.wxss",
  "./page/API/storage/storage.wxss", "./page/API/upload-file/upload-file.wxss",
  "./page/API/video/video.wxss",
  "./page/API/voice/voice.wxss",
  "./page/API/web-socket/web-socket.wxss",
  "./page/cart/index.wxss",
  "./page/component/component-pages/action-sheet/action-sheet.wxss",
  "./page/component/component-pages/button/button.wxss",
  "./page/component/component-pages/canvas/canvas.wxss",
  "./page/component/component-pages/checkbox/checkbox.wxss",
  "./page/component/component-pages/form/form.wxss",
  "./page/component/component-pages/icon/icon.wxss",
  "./page/component/component-pages/image/image.wxss",
  "./page/component/component-pages/input/input.wxss",
  "./page/component/component-pages/label/label.wxss",
  "./page/component/component-pages/navigator/navigator.wxss",
  "./page/component/component-pages/picker/picker.wxss",
  "./page/component/component-pages/progress/progress.wxss",
  "./page/component/component-pages/radio/radio.wxss",
  "./page/component/component-pages/scroll-view/scroll-view.wxss",
  "./page/component/component-pages/slide-tab/slide-tab.wxss",
  "./page/component/component-pages/swiper/swiper.wxss",
  "./page/component/component-pages/view/view.wxss",
  "./page/component/index.wxss",
  "./page/mytaobao/index.wxss",
  "./page/taobao/index.wxss",
];

export const testSuit: ITestSuit = {
  compilerConfig: {
    FILES,
    FILESBASE: path.join(__dirname, "./wechat-weapp-taobao"),
    cmd: ["-db", "-pc", FILES.length.toString()],
    outputDir: path.join(__dirname, "./out"),
    writeJs: false,
  },
  name: "suit64",
  units: [],
};
